# Generated by Django 2.2 on 2019-04-10 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.URLField(max_length=250, null=True)),
                ('country', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Estate', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(default='Update your bio', max_length=500)),
                ('extra_service', models.TextField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('Other', 'Other'), ('Non-Binary', 'Non-Binary')], max_length=20)),
                ('sexual_orientation', models.CharField(choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Lesbian', 'Lesbian'), ('Bisexual', 'Bisexual'), ('Pansexual', 'Pansexual'), ('Other', 'Other')], max_length=20)),
                ('ethnicity', models.CharField(choices=[('Latin', 'Latin'), ('Caucasian', 'Caucasian'), ('Black', 'Black'), ('White', 'White'), ('Middle East', 'Middle East'), ('Asian', 'Asian'), ('Indian', 'Indian'), ('Arabian', 'Arabian'), ('Aborgine', 'Aborgine'), ('Native American', 'Native American'), ('Other', 'Other')], max_length=20)),
                ('hair_color', models.CharField(choices=[('Black', 'Black'), ('Blonde', 'Blonde'), ('Brown', 'Brown'), ('Brunette', 'Brunette'), ('Chestnut', 'Chestnut'), ('Auburn', 'Auburn'), ('Dark-blonde', 'Dark-blonde'), ('Golden', 'Golden'), ('Red', 'Red'), ('Grey', 'Grey'), ('Silver', 'Silver'), ('White', 'White'), ('Other', 'Other')], max_length=20)),
                ('hair_length', models.CharField(choices=[('Bald', 'Bald'), ('Short', 'Short'), ('Shoulder', 'Shoulder'), ('Long', 'Long'), ('Very Long', 'Very Long')], max_length=20)),
                ('bust_size', models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large'), ('E+', 'Enormous')], max_length=2)),
                ('build', models.CharField(choices=[('Skinny', 'Skinny'), ('Slim', 'Slim'), ('Regular', 'Regular'), ('Curvy', 'Curvy'), ('Fat', 'Fat')], max_length=2)),
                ('looks', models.CharField(choices=[('Nothing Special', 'Nothing Special'), ('Average', 'Average'), ('Sexy', 'Sexy'), ('Ultra Sexy', 'Ultra Sexy')], max_length=2)),
                ('incall', models.BooleanField(default=False)),
                ('outcall', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('education_level', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=200)),
                ('services', models.TextField()),
                ('language_1', models.CharField(max_length=100)),
                ('language_2', models.CharField(max_length=100)),
                ('language_3', models.CharField(max_length=100)),
                ('language_1_fluency', models.CharField(choices=[('Minimal', 'Minimal'), ('Conversational', 'Conversational'), ('Fluent', 'Fluent')], max_length=20)),
                ('language_2_fluency', models.CharField(choices=[('Minimal', 'Minimal'), ('Conversational', 'Conversational'), ('Fluent', 'Fluent')], max_length=20)),
                ('language_3_fluency', models.CharField(choices=[('Minimal', 'Minimal'), ('Conversational', 'Conversational'), ('Fluent', 'Fluent')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
