# Generated by Django 2.2 on 2019-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0002_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='build',
            field=models.CharField(choices=[('Skinny', 'Skinny'), ('Slim', 'Slim'), ('Regular', 'Regular'), ('Curvy', 'Curvy'), ('Fat', 'Fat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looks',
            field=models.CharField(choices=[('Nothing Special', 'Nothing Special'), ('Average', 'Average'), ('Sexy', 'Sexy'), ('Ultra Sexy', 'Ultra Sexy')], max_length=20),
        ),
    ]
