# Generated by Django 2.2 on 2019-04-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0003_auto_20190410_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='create_guide_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='create_guide_profile.Profile'),
        ),
    ]
