# Generated by Django 2.2 on 2019-04-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0004_auto_20190410_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
