# Generated by Django 2.2 on 2019-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0005_auto_20190410_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
