# Generated by Django 2.2 on 2019-04-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='user',
        ),
    ]
