# Generated by Django 2.2 on 2019-04-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0011_auto_20190412_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='create_guide_profile.Profile'),
        ),
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_videos', to='create_guide_profile.Profile'),
        ),
    ]
