# Generated by Django 2.2 on 2019-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0012_auto_20190426_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='images-data'),
        ),
    ]
