# Generated by Django 2.2 on 2019-05-09 09:51

import create_guide_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0013_auto_20190505_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.FileField(upload_to='images-data'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='videos-data', validators=[create_guide_profile.validators.validate_file_size]),
        ),
    ]
