# Generated by Django 2.2 on 2019-05-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_guide_profile', '0014_auto_20190509_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='create_guide_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_videos', to='create_guide_profile.Profile'),
        ),
    ]
